version: 2

linters-settings:
  lll:
    line-length: 80
    tab-width: 1

linters:
  enable:
    - lll
    - govet
    - errcheck
    - staticcheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
