// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"workouts-backend/src/config"
	"workouts-backend/src/database"
	"workouts-backend/src/router"
)

// Injectors from wire.go:

func InitializeApp() (*gin.Engine, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := database.Connect(configConfig)
	if err != nil {
		return nil, err
	}
	engine := router.NewRouter(configConfig, db)
	return engine, nil
}
