// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"workouts-backend/src/config"
	"workouts-backend/src/database"
	"workouts-backend/src/handlers"
	"workouts-backend/src/router"

	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitializeApp() (*gin.Engine, error) {
	configConfig := config.Load()
	db, err := database.Connect(configConfig)
	if err != nil {
		return nil, err
	}
	healthHandler := handlers.NewHealthHandler(db)
	engine := router.NewRouter(configConfig, healthHandler)
	return engine, nil
}
